package com.jsf.entities;
// Generated 2019-02-19 14:33:32 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "chatapp")
public class Message implements java.io.Serializable {

	private Integer id;
	private User user;
	private Chat chat;
	private String text;
	private Date sendedAt;
	private Date recievedAt;

	public Message() {
	}

	public Message(User user, Chat chat) {
		this.user = user;
		this.chat = chat;
	}

	public Message(User user, Chat chat, String text, Date sendedAt, Date recievedAt) {
		this.user = user;
		this.chat = chat;
		this.text = text;
		this.sendedAt = sendedAt;
		this.recievedAt = recievedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userID", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chatID", nullable = false)
	public Chat getChat() {
		return this.chat;
	}

	public void setChat(Chat chat) {
		this.chat = chat;
	}

	@Column(name = "text", length = 45)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "sendedAt", length = 19)
	public Date getSendedAt() {
		return this.sendedAt;
	}

	public void setSendedAt(Date sendedAt) {
		this.sendedAt = sendedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recievedAt", length = 19)
	public Date getRecievedAt() {
		return this.recievedAt;
	}

	public void setRecievedAt(Date recievedAt) {
		this.recievedAt = recievedAt;
	}

}
